name: if release

on:
  push:
    branches: [master]
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: shellcheck
        run: shellcheck etesync/run.sh
      - name: hadolint
        run: docker run --rm -i hadolint/hadolint < etesync/Dockerfile
      - name: build docker files
        run: docker run --rm --privileged	-v /var/run/docker.sock:/var/run/docker.sock -v ~/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder	-t etesync	--amd64	--test
      - name: deploy docker files
        if: github.event_name != 'pull_request'
        run: docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock -v /home/travis/.docker:/root/.docker -v "$(pwd)":/data homeassistant/amd64-builder --target etesync --amd64 --release-tag --no-latest --docker-user sabuto --docker-password ${{ secrets.DOCKER_PASSWORD }}

  push-config-to-main-repo:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: main
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          path: main
      - name: secondary
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
          path: secondary
          repository: sabuto/hassio-repo

      - name: setup local env
        run: |
          \cp -Rv main/telegraf/config.json secondary/telegraf/config.json
          \cp -Rv main/README.md secondary/telegraf/README.md
          cd secondary
          git config --local user.email "robe_dunne@hotmail.com"
          git config --local user.name "sabuto"
          git add .
          git commit -m "Add changes"
        continue-on-error: true

      - name: copy config to repo dir in case of change
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_PSA }}
          repository: sabuto/hassio-repo
          directory: secondary
